monitor.alsa.rules = [
  {
    matches = [
      {
		# NVIDIA HDMI Audio
        device.name = "alsa_card.pci-0000_01_00.1"
      }
      {
		# Motherboard onboard audio
        device.name = "alsa_card.usb-Generic_USB_Audio-00"
      }
      {
		# iGPU HDMI Audio
        device.name = "alsa_card.pci-0000_0d_00.1"
      }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
]
