monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-Focusrite_Scarlett_Solo_USB_Y7QTA1T137B32A-00"
      }
    ]
    actions = {
      update-props = {
        device.profile = "pro-audio"
      }
    }
  }
]
