import = ["~/.dotfiles/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 18

[font.bold]
family = "NotoSansM Nerd Font Mono"
style = "SemiBold"

[font.bold_italic]
family = "Cascadia Code PL"
style = "Italic"

[font.italic]
family = "Cascadia Code PL"
style = "Light Italic"

[font.normal]
family = "NotoMono Nerd Font Mono"
style = "Regular"

[window]
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 4
y = 4
