# When Scarlett Solo is in "Pro Audio" configuration, the inputs are presented
# as a single stereo input channel. This config takes the right side of that
# and creates a virtual source with that channel on both left and right outputs.

context.modules = [
    {
        name = libpipewire-module-filter-chain

        args = {
            node.name = "scarlett_inst_stereo"
            node.description = "Scarlett Solo Jack"

            filter.graph = {
                nodes = [
                    {
                        type = builtin
                        name = copy
                        label = copy
                    }

                    {
                        type = builtin
                        name = left
                        label = mixer
                        control = {
                            "Gain 1" = 2.0
                        }
                    }

                    {
                        type = builtin
                        name = right
                        label = mixer
                        control = {
                            "Gain 1" = 2.0
                        }
                    }
                ]

                links = [
                    { output = "copy:Out" input = "left:In 1" }
                    { output = "copy:Out" input = "right:In 1" }
                ]

                inputs = [
                    "copy:In"
                ]

                outputs = [
                    "left:Out"
                    "right:Out"
                ]
            }

            capture.props = {
                node.name = "scarlett_inst_stereo_input"
                node.passive = true
                audio.channels = 1
                audio.position = [ FR ]

                target.object = "alsa_input.usb-Focusrite_Scarlett_Solo_USB_Y7QTA1T137B32A-00.pro-input-0"
            }

            playback.props = {
                node.name = "scarlett_inst_stereo"
                media.class = "Audio/Source"
                audio.channels = 2
                audio.position = [ FL FR ]
                stream.dont-remix = true
				device.icon-name = "audio-input-microphone"
            }
        }
    }
]
