# disable splash text rendering over the wallpaper
splash = false

# fully disable ipc
# ipc = off

wallpaper {
	monitor = HDMI-A-1
	path = /home/benallen/yoink/categorised/keep/wallhaven-96x28k.jpg
	fit_mode = cover
}

