[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 20

[font.bold]
family = "NotoSansM Nerd Font Mono"
style = "SemiBold"

[font.bold_italic]
family = "Caskaydia Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Caskaydia Mono Nerd Font"
style = "Italic"

[font.normal]
family = "NotoMono Nerd Font Mono"
style = "Regular"

[window]
option_as_alt = "Both"
dynamic_padding = true
opacity = 0.8
blur = true
decorations = "Full"
dynamic_title = true

[window.padding]
x = 4
y = 4
